#!/usr/bin/env python3
"""Module amalgamation: src/modules/ is the source, the app's module regions are output (D-30).

The app stays one hand-edited HTML file with no build step. A module is edited
only in its own folder under src/modules/, tested there on its own, and pasted
into the app unchanged by this tool, between a pair of markers that name it:

  // @module notes-store js 1.0.0 sha256=0123456789abcdef BEGIN: generated by tools/modules_embed.py from src/modules/notes-store/, do not edit here
  ...the module's banner, its file(s) unchanged, its end banner...
  // @module notes-store js END

(CSS regions use /* ... */ markers.) The tool replaces only what lies between a
module's own BEGIN and END lines. That closes the TD-238 failure mode, where
the grid re-paste rewrote everything from its banner to </style> and took a
neighbouring block with it.

src/modules/MODULES.json is the index: every module's version, files, global,
dependencies, tests, and where it goes in the app (slot and order). Its
"version" field is the one place a module's version is written; the marker
reads from it. The tool keeps a "recorded" block per module (the version and
source hashes at the last embed or stamp) so an edit to a module's source
without a version bump is caught.

  python3 tools/modules_embed.py                  # same as --check
  python3 tools/modules_embed.py --check          # exit 1 on any finding below
  python3 tools/modules_embed.py --embed [id ...] # paste modules in, record versions
  python3 tools/modules_embed.py --list           # index: id, version, status, position in the app
  python3 tools/modules_embed.py --extract ID --js-lines A-B [--css-lines C-D] --global NAME
                                                  # lift an app section out into src/modules/ID/

--check findings:
  TAMPERED    a module region in the app was edited by hand (its text no longer
              matches the hash in its BEGIN marker). Move the edit into the
              module source, then --embed.
  STALE       the module source or manifest changed since the last embed. Run --embed.
  UNVERSIONED a module source changed but its manifest version did not. Bump
              "version" in MODULES.json and add a changelog line to MODULE.md.
  MISSING     an embedded module has no region in the app.
  STRAY       a region in the app names a module the manifest does not embed.
  MISMATCH    a module folder has no manifest entry, or an entry has no folder.

--embed prints the app lines it rewrote; tools/run_checks.py then selects only
the checks covering those regions (docs/check-map.md).
"""
import argparse
import hashlib
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
APP = ROOT / "src" / "milestone-dashboard.html"
MODS = ROOT / "src" / "modules"
MANIFEST = MODS / "MODULES.json"

KINDS = {
    "js": ("// @module {id} js", "", "// @slot {slot}"),
    "css": ("/* @module {id} css", " */", "/* @slot {slot} */"),
}
BEGIN_RE = {
    "js": re.compile(r"^// @module (?P<id>[\w-]+) js (?P<ver>\S+) sha256=(?P<h>[0-9a-f]{16}) BEGIN\b.*$", re.M),
    "css": re.compile(r"^/\* @module (?P<id>[\w-]+) css (?P<ver>\S+) sha256=(?P<h>[0-9a-f]{16}) BEGIN\b.*\*/$", re.M),
}
END_LINE = {"js": "// @module {id} js END", "css": "/* @module {id} css END */"}
SEMVER = re.compile(r"^\d+\.\d+\.\d+$")


def h16(text):
    return hashlib.sha256(text.encode("utf-8")).hexdigest()[:16]


def load_manifest():
    return json.loads(MANIFEST.read_text(encoding="utf-8"))


def save_manifest(man):
    MANIFEST.write_text(json.dumps(man, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def module_dir(m):
    return MODS / m.get("dir", m["id"])


def source_files(m):
    """Every source file of the module (all kinds, embedded or not), relative to its folder."""
    out = []
    for kind in ("js", "css"):
        out += m.get("files", {}).get(kind, [])
    return out + m.get("extra_files", [])


def source_hashes(m):
    d = module_dir(m)
    return {f: (h16((d / f).read_text(encoding="utf-8")) if (d / f).exists() else None) for f in source_files(m)}


def region_text(m, kind):
    """The text between a module's BEGIN and END lines, built from its source files."""
    spec = m["embed"][kind]
    d = module_dir(m)
    names = spec.get("files", m["files"][kind])
    parts = []
    for n in names:
        p = d / n
        if not p.exists():
            sys.exit(f"{m['id']}: {p.relative_to(ROOT)} is missing.")
        t = p.read_text(encoding="utf-8").rstrip("\n")
        if kind == "js" and "</script" in t.lower():
            sys.exit(f"{m['id']}: {n} contains </script; the app would end its script there.")
        if kind == "css" and "</style" in t.lower():
            sys.exit(f"{m['id']}: {n} contains </style.")
        sep = spec.get("separator")
        parts.append((sep.format(name=n) + "\n" if sep else "") + t)
    head = spec.get("header", "").format(files=", ".join(names))
    body = "\n".join(parts)
    foot = spec.get("footer", "")
    return (head + "\n" if head else "") + body + ("\n" + foot if foot else "")


def begin_line(m, kind, text):
    pre, post, _ = KINDS[kind]
    return (pre.format(id=m["id"]) + f" {m['version']} sha256={h16(text)} BEGIN: generated by"
            f" tools/modules_embed.py from src/modules/{m.get('dir', m['id'])}/, do not edit here" + post)


def wrapped(m, kind, text):
    return begin_line(m, kind, text) + "\n" + text + "\n" + END_LINE[kind].format(id=m["id"])


def find_regions(src, kind):
    """{id: (start, end, version, hash, inner)}; start/end span the marker lines inclusive."""
    out = {}
    for b in BEGIN_RE[kind].finditer(src):
        mid = b.group("id")
        end = END_LINE[kind].format(id=mid)
        e = src.find("\n" + end, b.end())
        if e < 0:
            sys.exit(f"{mid} {kind}: BEGIN marker without END marker.")
        if mid in out:
            sys.exit(f"{mid} {kind}: two regions in the app.")
        inner = src[b.end() + 1:e]
        out[mid] = (b.start(), e + 1 + len(end), b.group("ver"), b.group("h"), inner)
    return out


def line_of(src, pos):
    return src.count("\n", 0, pos) + 1


def embedded(man):
    return [m for m in man["modules"] if m["status"] == "embedded"]


def check(man, src, quiet=False):
    findings = []
    ids = {m["id"] for m in man["modules"]}
    dirs = {m.get("dir", m["id"]) for m in man["modules"]}
    for d in sorted(p.name for p in MODS.iterdir() if p.is_dir()):
        if d not in dirs:
            findings.append(("MISMATCH", f"src/modules/{d}/ has no entry in MODULES.json"))
    for m in man["modules"]:
        if not module_dir(m).is_dir():
            findings.append(("MISMATCH", f"{m['id']}: folder {module_dir(m).relative_to(ROOT)} is missing"))
            continue
        if not SEMVER.match(m["version"]):
            findings.append(("MISMATCH", f"{m['id']}: version {m['version']!r} is not x.y.z"))
        for dep in m.get("deps", []):
            if dep not in ids:
                findings.append(("MISMATCH", f"{m['id']}: depends on unknown module {dep}"))
        rec = m.get("recorded")
        if rec:
            now = source_hashes(m)
            changed = sorted(f for f in now if now[f] != rec["sources"].get(f))
            if changed and rec["version"] == m["version"]:
                findings.append(("UNVERSIONED", f"{m['id']}: {', '.join(changed)} changed since {rec['version']} was recorded;"
                                 " bump its version in MODULES.json and add a MODULE.md changelog line"))
        else:
            findings.append(("UNVERSIONED", f"{m['id']}: no recorded version; run --embed"))
    for kind in KINDS:
        regions = find_regions(src, kind)
        want = {m["id"]: m for m in embedded(man) if kind in m.get("embed", {})}
        for mid in regions:
            if mid not in want:
                findings.append(("STRAY", f"{mid} {kind}: region in the app at line {line_of(src, regions[mid][0])}"
                                 " but the manifest does not embed it"))
        for mid, m in want.items():
            if mid not in regions:
                findings.append(("MISSING", f"{mid} {kind}: no region in the app; run --embed"))
                continue
            _, _, ver, hh, inner = regions[mid]
            at = line_of(src, regions[mid][0])
            if h16(inner) != hh:
                findings.append(("TAMPERED", f"{mid} {kind}: the region at line {at} was edited in the app."
                                 f" Move the edit into src/modules/{m.get('dir', mid)}/, then --embed"))
            elif inner != region_text(m, kind) or ver != m["version"]:
                findings.append(("STALE", f"{mid} {kind}: the region at line {at} is not the current source"
                                 f" ({ver} in the app, {m['version']} in the manifest); run --embed"))
    order_findings(man, src, findings)
    return findings


def order_findings(man, src, findings):
    """Within a slot, regions must sit in manifest order (load order: dependencies first)."""
    for kind in KINDS:
        regions = find_regions(src, kind)
        by_slot = {}
        for m in embedded(man):
            spec = m.get("embed", {}).get(kind)
            if spec and m["id"] in regions:
                by_slot.setdefault(spec["slot"], []).append((spec.get("order", 0), m["id"]))
        for slot, items in by_slot.items():
            want = [i for _, i in sorted(items)]
            have = sorted(want, key=lambda i: regions[i][0])
            if want != have:
                findings.append(("STALE", f"slot {slot} ({kind}): regions are in order {have}, manifest says {want}"))
    pos = {m["id"]: min((find_regions(src, k).get(m["id"], (10**12,))[0] for k in ("js",)), default=10**12)
           for m in embedded(man)}
    for m in embedded(man):
        for dep in m.get("deps", []):
            if dep in pos and pos[dep] > pos[m["id"]] and pos[m["id"]] < 10**12:
                findings.append(("STALE", f"{m['id']} loads before its dependency {dep}"))


def embed(man, src, only):
    changed = []
    for m in man["modules"]:
        if only and m["id"] not in only:
            continue
        if m["status"] == "embedded":
            for kind in m.get("embed", {}):
                regions = find_regions(src, kind)
                text = region_text(m, kind)
                new = wrapped(m, kind, text)
                if m["id"] in regions:
                    a, b, _, hh, inner = regions[m["id"]]
                    if h16(inner) != hh:
                        sys.exit(f"{m['id']} {kind}: TAMPERED at line {line_of(src, a)}. Refusing to overwrite a hand edit:"
                                 f" move it into src/modules/{m.get('dir', m['id'])}/ first.")
                    if src[a:b] == new:
                        continue
                elif src.count(text) == 1:
                    # Adopt an exact paste made before markers existed (the P75 banners).
                    a = src.index(text)
                    b = a + len(text)
                else:
                    slot = KINDS[kind][2].format(slot=m["embed"][kind]["slot"])
                    if src.count(slot) != 1:
                        sys.exit(f"{m['id']} {kind}: slot marker {slot!r} must appear exactly once in the app.")
                    a = b = src.index(slot)
                    # Before the first region in this slot that loads later (higher
                    # order); the slot marker is only right when none does. P79: once
                    # continue-file followed notes-history, a re-inserted notes-history
                    # landed after it and broke the slot's load order.
                    mine = m["embed"][kind]
                    later = [regions[o["id"]][0] for o in embedded(man)
                             if o["id"] != m["id"] and o["id"] in regions
                             and o.get("embed", {}).get(kind, {}).get("slot") == mine["slot"]
                             and o["embed"][kind].get("order", 0) > mine.get("order", 0)]
                    if later:
                        a = b = min(later)
                    new += "\n"
                src = src[:a] + new + src[b:]
                changed.append(f"{m['id']} {kind}: lines {line_of(src, a)}-{line_of(src, a + len(new))}")
        m["recorded"] = {"version": m["version"], "sources": source_hashes(m)}
    return src, changed


def extract(man, src, mid, js_lines, css_lines, glob, slot_js, slot_css):
    """Lift app lines into src/modules/<mid>/ unchanged and leave a marked region behind.

    A pure move: the module file holds exactly the lifted lines, so the app
    after --extract differs from before only by the two marker lines per kind.
    Making the lifted code a clean module (its own IIFE, one global, no app
    globals read) is a follow-up edit to the module file, versioned like any other.
    """
    if any(m["id"] == mid for m in man["modules"]):
        sys.exit(f"{mid} is already in the manifest.")
    d = MODS / mid
    if d.exists():
        sys.exit(f"{d.relative_to(ROOT)} already exists.")
    lines = src.split("\n")
    m = {"id": mid, "version": "0.1.0", "status": "embedded", "global": glob,
         "summary": "[CONFIRM] extracted from the app; describe its inputs and outputs in MODULE.md",
         "files": {}, "embed": {}, "deps": [], "tests": []}
    spans = []
    for kind, rng, slot in (("js", js_lines, slot_js), ("css", css_lines, slot_css)):
        if not rng:
            continue
        a, b = (int(x) for x in rng.split("-"))
        if not 1 <= a <= b <= len(lines):
            sys.exit(f"--{kind}-lines {rng} is outside the app.")
        spans.append((a, b, kind))
        m["files"][kind] = [f"{mid}.{kind}"]
        m["embed"][kind] = {"slot": slot, "order": 1000}
    spans.sort(reverse=True)
    d.mkdir(parents=True)
    for a, b, kind in spans:
        body = "\n".join(lines[a - 1:b])
        (d / f"{mid}.{kind}").write_text(body + "\n", encoding="utf-8")
        lines[a - 1:b] = wrapped(m, kind, body).split("\n")
    m["recorded"] = {"version": m["version"], "sources": source_hashes(m)}
    man["modules"].append(m)
    return "\n".join(lines)


def list_index(man, src):
    regions = {k: find_regions(src, k) for k in KINDS}
    print(f"{'id':<16}{'version':<10}{'status':<12}{'global':<18}app lines")
    for m in man["modules"]:
        where = []
        for k in KINDS:
            r = regions[k].get(m["id"])
            if r:
                where.append(f"{k} {line_of(src, r[0])}-{line_of(src, r[1])}")
        print(f"{m['id']:<16}{m['version']:<10}{m['status']:<12}{m.get('global', ''):<18}{'; '.join(where) or '-'}")


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    g = ap.add_mutually_exclusive_group()
    g.add_argument("--check", action="store_true")
    g.add_argument("--embed", nargs="*", metavar="ID")
    g.add_argument("--list", action="store_true")
    g.add_argument("--extract", metavar="ID")
    ap.add_argument("--js-lines")
    ap.add_argument("--css-lines")
    ap.add_argument("--global", dest="glob", default="")
    ap.add_argument("--slot-js", default="app-script-modules")
    ap.add_argument("--slot-css", default="style-modules")
    a = ap.parse_args()
    man = load_manifest()
    src = APP.read_text(encoding="utf-8")

    if a.list:
        list_index(man, src)
        return 0
    if a.extract:
        if not (a.js_lines or a.css_lines):
            ap.error("--extract needs --js-lines and/or --css-lines")
        out = extract(man, src, a.extract, a.js_lines, a.css_lines, a.glob, a.slot_js, a.slot_css)
        APP.write_text(out, encoding="utf-8")
        save_manifest(man)
        print(f"Extracted {a.extract} into src/modules/{a.extract}/ at 0.1.0. Write its MODULE.md before anything else.")
        return 0
    if a.embed is not None:
        unknown = set(a.embed) - {m["id"] for m in man["modules"]}
        if unknown:
            sys.exit(f"Unknown module(s): {', '.join(sorted(unknown))}")
        out, changed = embed(man, src, set(a.embed))
        if out != src:
            APP.write_text(out, encoding="utf-8")
        save_manifest(man)
        for c in changed:
            print("rewrote", c)
        print(f"Embedded {len(changed)} region(s); recorded versions. Next: python3 tools/run_checks.py")
        src = out

    findings = check(man, src)
    for kind, msg in findings:
        print(f"{kind:<12}{msg}")
    if findings:
        return 1
    if a.embed is None:
        print(f"Clean: {len(embedded(man))} embedded module(s) are their sources, pasted; every source change is versioned.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
