"""Generate docs/component-register.md from the region split and the ledger.

Per JS region: tie-in points (calls in and out, from a text scan; this is
documentation, the runner's selection uses executed coverage instead),
globals read and written, DOM ids touched, the checks that exercised it with
their last run and result, and the behaviour note (the comment directly above
the declaration). Then the coverage gap list: regions no check exercised.
"""
import datetime
import re

IDENT = re.compile(r"[A-Za-z_$][\w$]*")
ID_PATTERNS = [
    re.compile(r"getElementById\(\s*['\"]([\w-]+)['\"]"),
    re.compile(r"querySelector(?:All)?\(\s*['\"]#([\w-]+)"),
    re.compile(r"\$\(\s*['\"]([\w-]+)['\"]\s*\)"),
    re.compile(r"\bid=\\?[\"']([\w-]+)\\?[\"']"),
]
WRITE_OPS = r"(?:\s*(?:=(?!=)|\+=|-=|\*=|\|\|=|&&=|\?\?=|\+\+|--)|\.(?:push|splice|pop|shift|unshift|set|delete|clear|sort|length\s*=)\b|\[[^\]\n]{0,80}\]\s*=(?!=))"


def _strip_strings_comments(src):
    src = re.sub(r"/\*.*?\*/", " ", src, flags=re.S)
    src = re.sub(r"(?m)//.*$", " ", src)
    return src


def write(led, amap, path, suite):
    js = [r for r in amap.regs if r["kind"] == "js"]
    fn_names = {r["ident"] for r in js if r.get("fn")}
    glob_names = {r["ident"] for r in js if not r.get("fn") and not r["ident"].startswith("@js:")}
    toks = {}
    for r in js:
        body = _strip_strings_comments(r["text"])
        toks[r["name"]] = set(IDENT.findall(body))
    calls_in = {}
    for r in js:
        for t in toks[r["name"]]:
            if t in fn_names and t != r["ident"]:
                calls_in.setdefault(t, set()).add(r["ident"])
    cover = {}
    for cname, rec in led.get("checks", {}).items():
        for n, h in rec.get("used", {}).items():
            cover.setdefault(n, []).append((cname, rec, h))
    # markup handlers: onclick="fn()" and friends
    from_markup = {}
    for r in amap.regs:
        if r["kind"] == "markup":
            for t in set(IDENT.findall(" ".join(re.findall(r'\son\w+="([^"]*)"', r["text"])))):
                from_markup.setdefault(t, set()).add(r["name"][len("markup:"):])
    # a check that touched (nearly) every region of a kind - a CSSOM walk, a
    # querySelectorAll('*') - says nothing about which regions matter; leave it
    # out of the gap list so the gaps stay informative
    blanket = {}
    for k in ("css", "markup", "js"):
        total = sum(1 for r in amap.regs if r["kind"] == k) or 1
        for cname, rec in led.get("checks", {}).items():
            n = sum(1 for x in rec.get("used", {}) if x.split(":", 1)[0] == k)
            if n >= 0.95 * total:
                blanket.setdefault(k, []).append(cname)
    lines = []
    w = lines.append
    w("# Component register (generated)")
    w("")
    w("Generated by `python3 tools/run_checks.py` (or `--register`) from the region split of "
      "`src/milestone-dashboard.html` and `tools/check_map/ledger.json`. Do not edit by hand. "
      "How the runner uses this is in `docs/check-map.md`.")
    w("")
    w(f"Generated {datetime.datetime.now().astimezone().isoformat(timespec='seconds')}. "
      "Tie-in points, globals and DOM ids are a text scan (documentation only). "
      "**Covered by** lists checks whose recorded run actually executed the region; "
      "`stale` means the region changed since that run.")
    w("")
    counts = {}
    for r in amap.regs:
        counts[r["kind"]] = counts.get(r["kind"], 0) + 1
    w("| Region kind | Regions | Exercised by at least one check |")
    w("|---|---|---|")
    for k in ("js", "css", "markup", "vendor", "rest"):
        regs = [r for r in amap.regs if r["kind"] == k]
        cov = sum(1 for r in regs if r["name"] in cover)
        w(f"| {k} | {len(regs)} | {cov} |")
    w("")
    w("## JS regions")
    w("")
    for r in js:
        ident = r["ident"]
        kind = "function" if r.get("fn") else ("load-time chunk" if ident.startswith("@js:") else "declaration")
        w(f"### `{ident}`")
        w("")
        w(f"- **Kind:** {kind}. **Region:** `{r['name']}` hash `{r['hash']}`.")
        if r["note"]:
            w(f"- **Behaviour:** {r['note']}")
        else:
            w("- **Behaviour:**")
        out = sorted(t for t in toks[r["name"]] if t in fn_names and t != ident)
        inn = sorted(calls_in.get(ident, ()))
        w(f"- **Calls out:** {', '.join(out) if out else 'none'}")
        w(f"- **Called from:** {', '.join(inn) if inn else 'none found by text scan'}")
        if ident in from_markup:
            w(f"- **Bound in markup:** {', '.join(sorted(from_markup[ident]))}")
        body = _strip_strings_comments(r["text"])
        g = sorted(t for t in toks[r["name"]] if t in glob_names and t != ident)
        gw = [t for t in g if re.search(r"(?<![\w$.])" + re.escape(t) + WRITE_OPS, body)]
        gr = [t for t in g if t not in gw]
        w(f"- **Globals read:** {', '.join(gr) if gr else 'none'}")
        w(f"- **Globals written:** {', '.join(gw) if gw else 'none'}")
        ids = set()
        for pat in ID_PATTERNS:
            ids.update(pat.findall(r["text"]))
        w(f"- **DOM ids:** {', '.join('#' + i for i in sorted(ids)) if ids else 'none'}")
        cv = cover.get(r["name"], [])
        if cv:
            parts = []
            for cname, rec, h in sorted(cv):
                st = rec["result"]["status"]
                stale = "" if h == r["hash"] else ", stale"
                parts.append(f"{cname} ({rec['lastRun'][:16]}, {st}{stale})")
            if not r.get("fn"):
                w(f"- **Covered by:** every browser check ({len(cv)}), as load-time code")
            else:
                w(f"- **Covered by:** {'; '.join(parts)}")
        else:
            w("- **Covered by:** no check (coverage gap)")
        w("")
    w("## Coverage gaps")
    w("")
    w("Regions no recorded check exercised. A change to one of these selects no browser check "
      "through region coverage (static checks that read the whole file still run, and a check "
      "whose static-assertion literals it touches still runs).")
    w("")
    for k in ("js", "css", "markup"):
        bl = set(blanket.get(k, []))
        gaps = [r["name"] for r in amap.regs if r["kind"] == k
                and not any(c[0] not in bl for c in cover.get(r["name"], []))]
        w(f"### {k} ({len(gaps)})")
        w("")
        if bl:
            w(f"Not counting {', '.join(sorted(bl))}, which touched every {k} region "
              "(a stylesheet walk or an all-elements query), so they are selected by any change "
              "to these regions but say nothing about which ones a feature uses.")
            w("")
        for n in gaps:
            w(f"- `{n}`")
        w("")
    w("## Checks")
    w("")
    w("| Check | Kind | Last run | Commit | Result | Duration | Regions | Files |")
    w("|---|---|---|---|---|---|---|---|")
    for name, cmd in suite:
        rec = led.get("checks", {}).get(name)
        if not rec:
            w(f"| {name} | (no record) | | | | | | |")
            continue
        w(f"| {name} | {rec['kind']} | {rec['lastRun'][:16]} | {rec['commit']} | {rec['result']['status']} "
          f"({rec['result']['tail'][:40].replace('|', '/')}) | {rec['duration']}s | {len(rec['used'])} | "
          f"{len(rec['files'])} |")
    w("")
    path.write_text("\n".join(lines), encoding="utf-8")
